/* #undef FILLWAVE_COMPILATION_TINY_ASSET_LOADER */
/* #undef FILLWAVE_BACKEND_OPENGL_ES_20 */
#define FILLWAVE_BACKEND_OPENGL_ES_30
/* #undef FILLWAVE_BACKEND_OPENGL_45 */
#define FILLWAVE_COMPILATION_DRIVER_WORKAROUNDS
/* #undef FILLWAVE_COMPILATION_OPTIMIZE_RAM_USAGE */
/* #undef FILLWAVE_COMPILATION_OPTIMIZE_ONE_FOCUS */
#define FILLWAVE_COMPILATION_RELEASE
/* #undef FILLWAVE_TEXTURE_LOADER_CUSTOM */
#define FILLWAVE_MODEL_LOADER_ASSIMP
/* #undef FILLWAVE_MODEL_LOADER_TINYOBJLOADER */
/* #undef FILLWAVE_BENCHMARK_TESTS */
