/* This file is autogenerated, do not edit*/
#include "moc_Button.cpp"
#include "moc_Editorslider.cpp"
#include "moc_MainWidget.cpp"
#include "moc_Panel.cpp"
#include "moc_Renderer.cpp"
#include "moc_Sliders.cpp"
