#!/bin/bash
# Copyright (C) 2014, Dariusz Kluska <darkenk@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the {organization} nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

COPYRIGHT="Copyright (C) "$(date +"%Y")
RET=0
DIFF_FILES=`git diff --cached --name-only | grep -E "\.(java|cpp|c|h|s|hpp|cc)"`
COMMIT_MESSAGE=`git show -s --format=%s`

for i in ${DIFF_FILES}
do
    if [ -z "$(head -n 10 $i | grep "${COPYRIGHT}")" ]; then
        if [ ${RET} -eq 0 ]; then
            echo "Following files have missing copyright header: "
        fi
        echo $i
        RET=1
    fi
done

if [ ${RET} -ne 0 ]; then
    echo "Correct copyright should contains: ${COPYRIGHT}"
fi

if [ -z "$(echo $COMMIT_MESSAGE | grep "#")" ]; then
    if [ ${RET} -eq 0 ]; then
        echo "Commit message does not have issue id: #<ISSUE_ID>"
    fi
    RET=1
fi

DIFF=$(git diff-index --check --cached HEAD)
echo "${DIFF}" | sed -r 's/(^\+.*[[:graph:]]|[[:space:]])([[:space:]]+)$/\1\d27[32;41m\2\d27[37;40m/'
if [ -n "${DIFF}" ]; then
    RET=1
fi

if [ ${RET} -ne 0 ]; then
    if [ -e .git/hooks/fail-ascii-art.txt ]; then
        cat .git/hooks/fail-ascii-art.txt
    else
        echo "Your commit has errors"
    fi
else
    if [ -e .git/hooks/correct-ascii-art.txt ]; then
        cat .git/hooks/correct-ascii-art.txt
    else
        echo "Good job!"
    fi
fi
exit $RET
